spring.application.name=api-gatway

spring.application.name=api-gateway
server.port=8086
# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

